services:
  - type: worker
    name: govtjobs-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: 8155847480:AAHiRP1qzcK27SgIaY9kdSFN5QGMxct5sX0
      - key: ADMIN_ID
        value: 6593860853
      - key: CHANNEL_USERNAME
        value: "@Roboallbotchannel"
      - key: FETCH_INTERVAL_MINUTES
        value: 15
      - key: DATABASE_PATH
        value: govtjobs.db
